---
- name: Calling terraform to build resources
  hosts: localhost
  tasks:
#  - name: Basic deploy of a service
#    cloud.terraform.terraform:
#      project_path: './tf/'
#      state: present

  - name: Define the backend configuration at init
    cloud.terraform.terraform:
      project_path: './tf/'
      variables_file: '/vars/aws_vars.yml'
      state: "present"
      force_init: true
